# Conclusion

After working on this project, we were able to gather many different insights about football players through the use of the FIFA video game statistics/attributes. 

We were able to analyse the player heights and confirm their normal distribution for both men and women. We also saw that heights differed based on player position. Specifically, we saw (for women and men) that the goalkeeper tends to be the tallest player on the pitch. The forwards and wing players tend to be shorter (likely because speed is of more importance) while defenders tend to be taller (likely because of the necessity of heading the ball). Moreover, after performing dimensionality reduction using PCA, we saw that there are certain features that contribute more than others to a player having a better overall score and a higher market value. We then compared men and women salaries and confirmed the great disparities between them, something that must be seriously changed for the development of women football. Using the highcharter package, we checked where the best players were from and saw that Spain is by far the best country for young footballers in 2022, followed by Brazil, Argentina and France. Lastly, we saw that there are slight differences in the age distribution of the female and male players in 2022. We saw that the majority of male players are under the age of 25, while the majority of female players are between the ages of 25 and 30. 

Our study of football players was somewhat limited by the fact that we were using video game statistics. Although we can't be completely sure of it's accuracy (mostly in terms of the attribute ratings), the FIFA video game is the only place where there are statistical ratings/rankings of players. The analyses we did confirmed the assumptions that we had prior to starting this project, and also surprised us with some new insights. It would be amazing to be able to do more analysis of the different versions of the game (compare our results for FIFA15 to FIFA22) rather than solely concentrate on the latest version of the game. We would like to do more time series analyses of the data, focusing on how player ratings change over time. 

This project was extremely insightful as it allowed us to apply the different skills learned in class (data cleaning and transformation), D3 for the interactive component, and how to make impactful visualizations. We learned how to create interactive graphs, but with high-level and low-level programs, while also learning how to apply all of the skills we've learned over the semester to a real world (sometimes messy) dataset. 
