--- 
title: "Analysis of FIFA Players"
author: "Matthieu Schulz, Hugo Ginoux, Ryan McNamara"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Football is the most popular sport in the world. As football fans ourselves and because the World Cup is currently ongoing, we have chosen on working on questions surrounding this amazing sport for our final project. There are more than 240 million football players registered to a club and billions of more fans. Every 4 years an international tournament, The World Cup, captivates billions of fans from all countries, making it the most-watched sporting event around the globe. Football fans often try and compare their favorite players and one can easily gather information about their height, weight, salary, goals, etc., however, comparisons between players can become subjective and difficult without an official ranking.

FIFA, a video game franchise, allows one to simulate football matches (on PS5 and Xbox among others), provides rankings of players and their attributes. The game is released annually by Electronic Arts (EA), with updated players and statistics, is a fan favorite among sports video games. Unsurprisingly, FIFA is the highest-selling sports video game, selling 260 million copies as of 2022 (the next highest is Madden, with over 130 million copies sold) ([source](<https://www.rookieroad.com/sports/top-10-sports-video-games/>)). 

While specific ratings are not available in the real world of football, using the data from the FIFA video games allows us to analyze players and their skills in a more quantitative, rather than qualitative, way. The tremendous interest in football worldwide makes this a fascinating topic with a plethora of insights to uncover. 




