# Interactive Component 

<script src="https://d3js.org/d3.v7.js"></script>

<p>We are going to look at the age distribution of the males and female players in the year 2022. In order to look at the age distribution of the other gender, simply click on the radio button below!</p>

<p>Select a gender</p>
<input type="radio" id="male" name="gender" value="Male" checked>
<label for="male">Male</label><br>
<input type="radio" id="female" name="gender" value="Female">
<label for="female">Female</label><br>

<div id="plot"></div>

<p>We can see that the majority of male playrs in the year 2022 are less than 25 years old. A lot of the most exciting players in the game (i.e. Mbappé, Alphonso Davies, Phil Foden, etc.) are less than 25 years old. This is not surprising since players begin attending soccer academies before they are even 10 years old. The game is built around speed and quickness, and young legs tend to dominate in these areas. We see that there are very few players over 30 (Messi and Ronaldo being two of them). While a few veterans that can supply leadership (especially in the international game) are cherished on every team, they are usually surrounded by younger, more lively players. 

Interestingly, we see that the most populated age group for the women is 25-30. Like the men, there are very few female soccer players that are above the age of 30, and quite a few that are younger than 25. Like we mentioned earlier, the women's game is often more cerebral, possibly contributing to the differences we see from the men. There are plenty of star female players that are young and spry, even between the ages of 25-30. Some examples include Fridolina Rolfo, Lucy Bronze, Lindsey Horan, and Sam Kerr. There is often more money poured into the male game (unfortunately), so women might not begin training as early. All in all, it seems that women become better with time, reaching their most dominant in their late 20s. This is slightly different from the men's game, where young legs dominate the pitch.

<script>
  
const w = 600; 
const h = 400; 
const margin = {top: 50, 
  right: 0, 
  bottom: 45, 
  left: 55};

const innerWidth = w - margin.left - margin.right; 
const innerHeight = h - margin.top - margin.bottom; 


// dataset

const male_data = [{age: "<25", value: 0.557}, 
  {age: "25-30", value: 0.291}, 
  {age: "30-35", value: 0.132}, 
  {age: ">35", value: 0.020}];

const female_data = [
  {age: "<25", value: 0.358}, 
  {age: "25-30", value: 0.442}, 
  {age: "30-35", value: 0.171}, 
  {age: ">35", value: 0.029}];
  

const xScale = d3.scaleBand()
  .domain(male_data.map(d => d.age))
  .range([0, innerWidth])
  .paddingInner(0.1);
  
const yScale = d3.scaleLinear()
  .domain([0, 1])
  .range([innerHeight, 0]);
  
const xAxis = d3.axisBottom()
  .scale(xScale);
  
const yAxis = d3.axisLeft()
  .scale(yScale);
  
// add svg 
  
const svg = d3.select('div#plot')
  .append('svg')
  .attr('width', w)
  .attr('height', h);
    
// add background rectangle

svg.append('rect')
  .attr('x', 0)
  .attr('y', 0)
  .attr('width', w)
  .attr('height', h)
  .attr('fill', 'aliceblue');
    
const bars = svg.append('g') 
  .attr('id', 'plot')
  .attr('transform', `translate (${margin.left}, ${margin.top})`)
  .selectAll('rect')
  .data(male_data);
    
bars.enter().append('rect')
  .attr('x', d => xScale(d.age))
  .attr('y', d => yScale(d.value))
  .attr('width', xScale.bandwidth())
  .attr('height', d => innerHeight - yScale(d.value))
  .attr('fill', 'lightgreen');
    
// add axes 

svg.append('g') 
  .attr('class', 'xAxis')
  .attr('transform', `translate (${margin.left}, ${h - margin.bottom})`)
  .call(xAxis);
    
svg.append('g')
  .attr('class', 'yAxis')
  .attr('transform', `translate (${margin.left}, ${margin.top})`)
  .call(yAxis);
  
// add labels 

  svg.append('g')
    .attr('id', 'xlabel')
    .append('text')
    .attr('x', 282.5)
    .attr('y', 390)
    .text('Player Age')
    .attr('fill', 'black')
    
  svg.append('g')
    .attr('id', 'ylabel')
    .append('text')
    .attr("transform", "translate(20,240) rotate(270)")
    .text('Fraction of Players')
    .attr('fill', 'black');
    
  svg.append('g')
    .attr('id', 'title')
    .append('text')
    .attr('x', 82)
    .attr('y', 20)
    .attr('transform', 'scale(1.5)')
    .text('Proportion of Male Players by Age')
    .attr('fill', 'black')
    
  d3.selectAll('input')
    .on('click', function(event) {
      var gender = event.currentTarget.value;
      d3.select('g#title')
        .select('text')
        .text(`Proportion of ${gender} Players by Age`);
        
      if (gender == 'Female') {
      
        d3.select('g#plot').selectAll('rect')
          .data(female_data)
          .attr('x', d => xScale(d.age))
          .attr('y', d => yScale(d.value))
          .attr('width', xScale.bandwidth())
          .attr('height', d => innerHeight - yScale(d.value))
          .attr('fill', 'lightgreen');
      }
      
      if (gender == 'Male') {
      
        d3.select('g#plot').selectAll('rect')
          .data(male_data)
          .attr('x', d => xScale(d.age))
          .attr('y', d => yScale(d.value))
          .attr('width', xScale.bandwidth())
          .attr('height', d => innerHeight - yScale(d.value))
          .attr('fill', 'lightgreen');
      }
        
  });
  
  
    
    

</script>
