# Proposal

## Research topic


The amount of data that is contained in FIFA video games is colossal. For instance, the newest release, FIFA 23, features more than 19,000 players across 700 teams. Each of these players is assigned specific ratings for over 100 attributes, such as speed, strength, mentality, striking, goalkeeping, etc. Moreover, since 2016, the game has included female players and female teams.

The vast amount of data that is present in one of these games is enough to conduct a variety of compelling analysis and visualizations. The specific ratings given to each player allow us to explore correlations and patterns between variables. A few possible ways to analysis the data (more of this in 2.2) are: seeing how overall rating influences salary, what the height distribution is by position, and how specific players' ratings changed over time.

## Data availability

For the purpose of this project, we will be using the following FIFA datasets: <https://sports-statistics.com/soccerl/fifa-2022-dataset-csvs/>

Electronic Arts Website: <https://www.ea.com/sports>

FIFA is updated yearly with a new release (i.e. FIFA 21 for 2021, FIFA 22 for 2022, etc.). Thus, the players, teams, and ratings are kept current with each release. The origin of the data is the Electronic Arts company, which determines the ratings of teams and players and creates the game every year. Although the game is created by Electronic Arts, the datasets we are going to use were curated by a website called sports-statistics.com. More specifically, our datasets were created by Thomas Nielson, a writer for the website. In order to create the datasets, the author scraped the data for each player from a website called [sofifa.com](sofifa.com). This website keeps track of each players attributes/ratings for each release of the FIFA video game. The data we are using is scraped directly off of this website with minimal preprocessing/cleaning.

The website sports-statistics.com appears to be a reliable website that provides datasets for different sports, including basketball, baseball, football, and soccer. Our specific datasets were included in a short article written by Thomas Nielson, who writes for the website and has published many other sports datasets. We found multiple other websites (including [Data World](<https://data.world/datasets/fifa>) and [Kaggle](<https://www.kaggle.com/datasets/stefanoleone992/fifa-21-complete-player-dataset>)) that provided datasets of FIFA players. However, these datasets did not include multiple years, were filtered and preprocessed already, or were not consistently udated. If we have any questions or concerns about our datasets, we can directly contact the website and Thomas Nielson via a "Contact Us" link on their website.

A brief explanation of the format of the dataset is given below:

The dataset that we are going to use for this project is actually a collection of datasets. We have identified datasets documenting important player statistics from the FIFA video games for both the male and female players in the game. Each dataset contains the data for a single release of the FIFA video game (i.e. a particular year). For the male players, we have 8 datasets that correspond to the years 2015 through 2022. For the female players, we have 7 datasets that correspond to the years 2016 through 2022 (female players and teams were introduced in FIFA 2016). Each dataset contains the same number and type of features.

Each row of the dataset corresponds to a player, and they are ordered in decreasing overall rating. There are over 100 features (columns) in each of the datasets. A few of the columns are as follows: name, position (both for a club team and national team), foot preference, height, weight, wage, value, overall rating, attribute ratings (i.e. attacking, defending, striking, goalkeeping, speed, dribbling, stamina, mentality, etc.), nationality, etc. The dataset also contains a column for links to the [website](https://sofifa.com/players) that the player attributes/ratings were collected from.

A few of the columns are formatted in a way that is not optimal for data analysis and visualization, so preprocessing and cleaning will be necessary. For example, for players that play multiple positions, their positions are under the same column and separated with a comma. Also, player tags are included with a '\#' preceding them and multiple are included in the same column. We obviously will not use every attribute that is present in the dataset, and thus we must clean the columns we wish to use and discard the rest.

We plan on conducting analyses of player statistics from the year 2022, along with temporal analyses across the releases. In order to do this, we will combine all of the datasets after adding a "year" column. The concatenation should be simple using "rbind." The datasets are available in two different formats: as individual CSV files and as a single Excel file with sheets corresponding to the years. We prefer to use the CSV files since having individual files for each year is more organized. With this simple format, we will import the datasets into R using the "read_csv" function in R. Using this function, we will easily be able to view the datasets as individual data.frames before concatenating them.

Following are some ideas we have for data exploration:

-   We are interested in exploring the height distribution of players based on their position for both men and women. Is height preferred in some positions more than others? In what positions does height provide an advantage for performance?
-   We are interested in performing dimensionality reduction using PCA to see if we can identify clusters of players that have similar skill sets. If we color code points based on position, do we see those positions grouped together in the biplot based on their attribute ratings?
-   How does overall rating influence player salary? Are there specific attributes that are more desirable and lead to a higher salary?
-   How do the salaries compare between men and women? This can be explored in a few ways: comparing all men to all women, comparing within the same country, comparing between counties, and comparing based on the overall rating.
-   How do the ratings of our favorite players change over time, both overall and for specific attributes? Which attributes are negatively correlated and which are positively correlated? For example: as age increases, speed might decrease while mentality increases.
